reservalacancha/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    #site urls
    url(r'^$', 'website.views.index'),
    url(r'^register/$', 'website.views.register'),
    url(r'^search/$', 'website.views.search'),
    url(r'^cancha/$', 'website.views.detail'),
    url(r'^reservar/$', 'website.views.reserve'),
    url(r'^reservas/$', 'website.views.my_reserves_client'),
    url(r'^reservaspropietario/$' , 'website.views.my_reserves_propietary'),
    url(r'^moderar/$', 'website.views.moderate_reserve'),
    url(r'^miscanchas/$', 'website.views.mis_canchas'),
    url(r'^cancha/eliminar/$', 'website.views.eliminar_cancha'),
    url(r'^cancha/crear/$', 'website.views.crear_cancha'),
    url(r'^cancha/modificar/(?P<id_cancha>\d+)$', 'website.views.modificar_cancha'),
    url(r'^complejo/crear/$', 'website.views.crear_complejo'),
    url(r'^complejo/(?P<id_complejo>\d+)$', 'website.views.detalle_complejo'),
    url(r'^recuperar/$', 'website.views.recovery'),
    #admin urls
    url(r'^admin/', include(admin.site.urls)),
    #auth urls
    url(r'^login/$', login),
	url(r'^logout/$', logout, {'next_page': '/'}),


)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
    )

website/models.py
#encoding:utf-8
from django.db import models
from django.contrib.auth.models import User

class Deporte(models.Model):

	nombre = models.CharField(max_length=50)

	def __unicode__(self):
		return self.nombre

class Complejo(models.Model):

	nombre = models.CharField(max_length=50)
	direccion = models.CharField(max_length=100)
	latitud = models.FloatField(null=True, blank=True)
	longitud = models.FloatField(null=True, blank=True)
	duenio = models.ForeignKey(User)

	def __unicode__(self):
		return self.nombre


class Cancha(models.Model):

	#tupla para manejar los horarios
	hora_opciones=(
		('0','00.00 hs'), ('1','01.00 hs'), ('2','02.00 hs'),
		('3','03.00 hs'), ('4','04.00 hs'), ('5','05.00 hs'),
		('6','06.00 hs'), ('7','07.00 hs'), ('8','08.00 hs'),
		('9','09.00 hs'), ('10','10.00 hs'), ('11','11.00 hs'),
		('12','12.00 hs'), ('13','13.00 hs'), ('14','14.00 hs'),
		('15','15.00 hs'), ('16','16.00 hs'), ('17','17.00 hs'),
		('18','18.00 hs'), ('19','19.00 hs'), ('20','20.00 hs'),
		('21','21.00 hs'), ('22','22.00 hs'), ('23','23.00 hs'),
	)

	hora_comienzo_atencion = models.CharField(max_length=4,choices=hora_opciones)
	hora_fin_atencion = models.CharField(max_length=4,choices=hora_opciones)
	precio_por_turno = models.FloatField()
	imagen =  models.ImageField(upload_to='canchas', verbose_name='Imágen')
	deporte = models.ForeignKey(Deporte)
	complejo = models.ForeignKey(Complejo)
	numero_cancha = models.IntegerField(blank=True, null=True)

	def save(self, *args, **kwargs):

		if not self.pk:
			no = Cancha.objects.filter(complejo=self.complejo, deporte=self.deporte).count()
			if no == None:
				self.numero_cancha = 1
			else:
				self.numero_cancha = no + 1

		super(Cancha, self).save(*args, **kwargs)

	

	def __unicode__(self):
		return 'Complejo: ' + self.complejo.nombre + ' - Deporte: ' + self.deporte.nombre + ' - Cancha: ' + str(self.numero_cancha)

	def get_open(self):

		horas = [0 , 1 , 2 , 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
		inicio = int(self.hora_comienzo_atencion)
		fin = int(self.hora_fin_atencion)

		return horas[inicio:fin]


class Reserva(models.Model):

	#tupla para manejar los horarios
	hora_opciones=(
		('0','00.00 hs'), ('1','01.00 hs'), ('2','02.00 hs'),
		('3','03.00 hs'), ('4','04.00 hs'), ('5','05.00 hs'),
		('6','06.00 hs'), ('7','07.00 hs'), ('8','08.00 hs'),
		('9','09.00 hs'), ('10','10.00 hs'), ('11','11.00 hs'),
		('12','12.00 hs'), ('13','13.00 hs'), ('14','14.00 hs'),
		('15','15.00 hs'), ('16','16.00 hs'), ('17','17.00 hs'),
		('18','18.00 hs'), ('19','19.00 hs'), ('20','20.00 hs'),
		('21','21.00 hs'), ('22','22.00 hs'), ('23','23.00 hs'),
	)

	hora = models.CharField(max_length=4,choices=hora_opciones)
	fecha = models.DateField()
	estado = models.CharField(max_length=50)
	cancha = models.ForeignKey(Cancha)
	usuario = models.ForeignKey(User)

	def __unicode__(self):
		return 'Usuario: ' + self.usuario.username + ' - Fecha: ' + self.fecha.strftime("%Y-%m-%d") + ' - Cancha: ' + self.cancha.nombre

website/forms.py
#encoding:utf-8
from django import forms
from django.forms import PasswordInput, TextInput, HiddenInput
from django.contrib.auth.models import User
from website.models import Cancha, Complejo


class UserForm(forms.ModelForm): 
    class Meta: 
         model =  User
         fields = (
         	'username', 
         	'first_name', 
         	'last_name',
         	'email',
         	'password')
         widgets = {
            'password': PasswordInput()
        	} 

    def save(self, commit=True):
        
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(u'La dirección de correo ya existe. La misma debe ser única')
        return email

class CanchaForm(forms.ModelForm): 
    class Meta: 
         model =  Cancha
         widgets = {
            'numero_cancha': HiddenInput()
         }

class ComplejoForm(forms.ModelForm):
    class Meta:
        model = Complejo
        widgets = {
            'direccion': HiddenInput(),
            'latitud': HiddenInput(),
            'longitud': HiddenInput(),
            'duenio': HiddenInput()
         }

class RecoveryForm(forms.Form):

        usuario = forms.CharField()

website/views.py
#encoding:utf-8
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from website.models import Deporte, Cancha, Reserva, Complejo
from forms import UserForm, CanchaForm, ComplejoForm, RecoveryForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import Group
import time
from datetime import date
from datetime import datetime
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, login 
from django.contrib import messages
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
import string
import random

#saber si un usuario es cliente
def is_client(user):
    return user.groups.filter(name='Clientes').exists()

def is_propiertario(user):
    return user.groups.filter(name='Propietarios').exists()

#pagina principal
def index(request):

	if is_propiertario(request.user):
		return redirect("/miscanchas")
	user = request.user
	complejos = Complejo.objects.all()

	return render_to_response('index.html', 
		{'complejos': complejos, 
		'user': user},
        context_instance=RequestContext(request))
 
#registro de usuarios
def register(request):

	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			group = request.POST['group']
			print 'choice ' + group
			u = form.save()
			g = Group.objects.get(name=group) 
			g.user_set.add(u)

			u = authenticate(username=request.POST['username'],
				password=request.POST['password'])
			login(request, u)

			return HttpResponseRedirect('/')
	else:
		form = UserForm()
	
	return render_to_response('register.html', 
		{'form': form},
		context_instance=RequestContext(request))

#listado de canchas de un determinado deporte
def search(request):
	query = request.GET.get('q', '')
	user = request.user
	results = []
	if query:
		deporte = Deporte.objects.filter(nombre__icontains=query).distinct()
		if deporte:
			results = Cancha.objects.filter(deporte=deporte)

	return render_to_response('list_canchas_cliente.html',
		{'results': results, 
		'user': user,
		'q': query}, 
		context_instance=RequestContext(request))


#detalle de una determinada cancha para una determinada fecha
@login_required(login_url='/login/')
@user_passes_test(is_client)
def detail(request):
	user = request.user
	id_cancha = request.GET.get('id', '-1')
	cancha = get_object_or_404(Cancha, pk=id_cancha)
	
	fecha = request.GET.get('date', time.strftime("%Y-%m-%d"))
	fecha_lista = fecha.split('-')

	reservas = Reserva.objects.filter(
		cancha=cancha, 
		fecha__year=fecha_lista[0],
		fecha__month=fecha_lista[1],
		fecha__day=fecha_lista[2]).exclude(
		estado='Cancelada por el Cliente').exclude(
		estado='Rechazada por Propietario')

	horas_abierto = cancha.get_open()
	horas_reservadas = []

	for reserva in reservas:
		horas_reservadas.append(int(reserva.hora))

	horas_disponibles = [item for item in horas_abierto if item not in horas_reservadas]
	
	return render_to_response('detail.html', 
		{'cancha': cancha, 
		'user': user,
		'fecha': fecha,
		'disponibles': horas_disponibles,
		'fecha_actual': time.strftime("%Y-%m-%d")},
        context_instance=RequestContext(request))

#crea reserva a una determinada cancha
@login_required(login_url='/login/')
@user_passes_test(is_client)
def reserve(request):

	fecha = request.POST['fecha'].split('-')
	id_cancha = request.POST['id_cancha']

	hora = request.POST['hora']
	fecha = date(int(fecha[0]), int(fecha[1]), int(fecha[2]))
	estado = 'Pendiente de aprobacion'
	cancha = get_object_or_404(Cancha, pk=id_cancha)
	user = request.user

	reserva = Reserva(
		hora=hora,
		fecha=fecha,
		estado=estado,
		cancha=cancha,
		usuario=user
		)
	reserva.save()
	messages.info(request, "Tu reserva fue realizada con exito")

	#aqui se envia un mail informando la reserva al propietario
	body = 'Datos de la reserva:' + '\n'
	body = body + 'Complejo: ' + reserva.cancha.complejo.nombre + '\n'
	body = body + 'Deporte: ' + reserva.cancha.deporte.nombre + '\n'
	body = body + 'Cancha: ' + str(reserva.cancha.numero_cancha) + '\n'
	body = body + 'Fecha: ' + reserva.fecha.strftime('%d-%m-%Y')+ '\n'
	body = body + 'Hora: ' + reserva.hora + ':00hs' '\n \n'
	body = body + 'Datos del cliente: ' + '\n'
	body = body + 'Nombre de usuario: ' + reserva.usuario.username + '\n'
	body = body + 'Nombre: ' + reserva.usuario.first_name + '\n'
	body = body + 'Apellido: ' + reserva.usuario.last_name + '\n'
	body = body + 'Correo: ' + reserva.usuario.email + '\n'
	
	propietario = reserva.cancha.complejo.duenio
	email_enviar = EmailMessage(
		subject='¡Tienes una nueva reserva!', 
		body= body, 
		to=[propietario.email])

	email_enviar.send()
	
	return redirect('/reservas')

#visualizar reservas
@login_required(login_url='/login/')
@user_passes_test(is_client)
def my_reserves_client(request):
	
	user = request.user
	reservas = Reserva.objects.filter(usuario=user).order_by('-id')

	return render_to_response('list_reserves_client.html',
		{'results': reservas,
		'user': user,
		'today': datetime.now()},
		context_instance=RequestContext(request))		


#moderar reservas
@login_required(login_url='/login/')
def moderate_reserve(request):
	
	user = request.user
	#constantes de posibilidades de estado
	cancelada = 'Cancelada por el Cliente'
	rechazada = 'Rechazada por Propietario'
	aprobada = 'Aprobada por el propietario'

	if is_client(user) or is_propiertario(user):
		id_reserva = request.POST.get('id_reserva', '-1')
		reserva = get_object_or_404(Reserva, pk=id_reserva)
		reserva.estado = request.POST.get('estado')
		reserva.save()
		messages.info(request, "Haz cambiado el estado de la reserva exitosamente")

		#se envia un mail informando del cambio de estado
		body = 'Datos de la reserva:' + '\n'
		body = body + 'Complejo: ' + reserva.cancha.complejo.nombre + '\n'
		body = body + 'Deporte: ' + reserva.cancha.deporte.nombre + '\n'
		body = body + 'Cancha: ' + str(reserva.cancha.numero_cancha) + '\n'
		body = body + 'Fecha: ' + reserva.fecha.strftime('%d-%m-%Y')+ '\n'
		body = body + 'Hora: ' + reserva.hora + ':00hs' '\n \n'

		subject = 'Reserva ' + reserva.estado

		if reserva.estado == rechazada or reserva.estado == aprobada:
			to = reserva.usuario.email
		else:
			to = reserva.cancha.complejo.duenio.email
			body = body + 'Datos del cliente: ' + '\n'
			body = body + 'Nombre de usuario: ' + reserva.usuario.username + '\n'
			body = body + 'Nombre: ' + reserva.usuario.first_name + '\n'
			body = body + 'Apellido: ' + reserva.usuario.last_name + '\n'
			body = body + 'Correo: ' + reserva.usuario.email + '\n'

		email_enviar = EmailMessage(
			subject=subject, 
			body= body, 
			to=[to])

		email_enviar.send()

	if is_client(user):
		return redirect('/reservas')
	elif is_propiertario(user):
		return redirect('/reservaspropietario')

#muestra las canchas de un propietario
@login_required(login_url='/login/')
@user_passes_test(is_propiertario)
def mis_canchas(request):

	user = request.user
	complejos = Complejo.objects.filter(duenio=user)
	results = Cancha.objects.filter(complejo=complejos).order_by('-id')

	return render_to_response('list_canchas_propietario_1.html',
		{'results': results,
		'complejos': complejos,
		'user': user,
		'today': datetime.now()},
		context_instance=RequestContext(request))


#elimina la cancha de un propietario		
@login_required(login_url='/login/')
@user_passes_test(is_propiertario)
def eliminar_cancha(request):

	user = request.user
	id_cancha = request.POST.get('id_cancha', '-1')
	cancha = get_object_or_404(Cancha, pk=id_cancha)

	if cancha.complejo.duenio == user:
		cancha.delete()

	return redirect('/miscanchas')

#visualizar reservas para un propietario
@login_required(login_url='/login/')
@user_passes_test(is_propiertario)
def my_reserves_propietary(request):
	
	user = request.user
	complejos = Complejo.objects.filter(duenio=request.user)
	canchas_propietario = Cancha.objects.filter(complejo__in=complejos)

	reservas = Reserva.objects.filter(cancha__in=canchas_propietario).order_by('-id')

	return render_to_response('list_reserves_propietario.html',
		{'results': reservas,
		'user': user,
		'today': datetime.now()},
		context_instance=RequestContext(request))


#Creacion canchas
@login_required(login_url='/login/')
@user_passes_test(is_propiertario)
def crear_cancha(request):

	if request.method == 'POST':
		form = CanchaForm(request.POST, request.FILES)
		if form.is_valid():
			c = form.save()
			return HttpResponseRedirect('/')
	else:
		form = CanchaForm()
		form.fields["complejo"].queryset = Complejo.objects.filter(duenio=request.user)	
	
	return render_to_response('create_cancha.html', 
		{'form': form},
		context_instance=RequestContext(request))

@login_required(login_url='/login/')
@user_passes_test(is_propiertario)
def modificar_cancha(request, id_cancha):

	cancha = get_object_or_404(Cancha, pk=id_cancha)

	if request.method == 'POST':
		form = CanchaForm(request.POST, request.FILES, instance=cancha)
		if form.is_valid():
			c = form.save()
			return HttpResponseRedirect('/')
	else:
		form = CanchaForm(instance=cancha)
		form.fields["complejo"].queryset = Complejo.objects.filter(duenio=request.user)	

	
	return render_to_response('edit_cancha.html', 
		{'form': form},
		context_instance=RequestContext(request))


@login_required(login_url='/login/')
@user_passes_test(is_propiertario)
def crear_complejo(request):

	if request.method == 'POST':
		form = ComplejoForm(request.POST)
		if form.is_valid():
			c = form.save()
			return HttpResponseRedirect('/')
	else:
		form = ComplejoForm(initial={'duenio': request.user})		
	
	return render_to_response('create_complejo.html', 
		{'form': form},
		context_instance=RequestContext(request))

def detalle_complejo(request, id_complejo):

	complejo = get_object_or_404(Complejo, pk=id_complejo)
	results = Cancha.objects.filter(complejo=complejo)

	return render_to_response('detalle_complejo.html',

website/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
			<meta charset="utf-8">
			<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
			<title>{% block title %}{% endblock title %}</title>
			<meta name="description" content="">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
			<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-theme.min.css">
			<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    		<!-- Include all compiled plugins (below), or include individual files as needed -->
    		<script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
			<style type="text/css" media="screen">
			  <!--
			  .navbar {
			    margin-bottom: 0;
			  }
			  .jumbotron {
			    margin-bottom: 0;
			  }

			  body{
			  	background-color: #eee
			  }
			-->
			</style> 

			{% block head %}{% endblock head %}
	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">
		      	<img src="{{STATIC_URL}}img/logo.png">
		      </a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		   	{% block nav_links %}
		      <ul class="nav navbar-nav">

		      {% if user.groups.all.0.name == 'Clientes' %}
					<li><a href="/">Inicio</a></li>
					<li><a href="/reservas">Mis Reservas</a></li>
			  {% elif user.groups.all.0.name == 'Propietarios' %}
			  		<li><a href="/miscanchas">Mis canchas</a></li>
					<li><a href="/reservaspropietario">Moderar Reservas</a></li>
			  {% endif %}
			  </ul>
		     {% endblock nav_links %}
		      <ul class="nav navbar-nav navbar-right">
		      {% block nav_right %}
		      {% if user.is_authenticated %}
				<li>
					<div class="dropdown">
						<button class="btn btn-default dropdown-toggle navbar-btn" type="button" id="dropdownMenu1" data-toggle="dropdown">
							{% if user.first_name %}
								{{user.first_name}}
							{% else %}
								{{user.username}}
							{% endif %}
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
						<!--	<li role="presentation">
								<a role="menuitem" tabindex="-1" href="/password_change/">
									Cambiar contrase&ntilde;a
								</a>
							</li>

							<li role="presentation" class="divider"></li>-->
							<li role="presentation">
								<a role="menuitem" tabindex="-1" href="/logout">
									Cerrar sesi&oacute;n
								</a>
							</li>
						</ul>
					</div>
				</li>
				{% else %} 
			
				<div >
					<a class="btn btn-default navbar-btn" href="/register">Registrarse</a>
					<a class="btn btn-primary navbar-btn" href="/login">Iniciar sesi&oacute;n</a>
				</div>
				{% endif %}  
		      {% endblock nav_right %}
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
		
		{% block body %}{% endblock body %}


    {% block extra_js %}{% endblock extra_js %}
	</body>
</html>

website/templates/create_cancha.html
{% extends "base.html" %}
{% block title %}Crear Cancha{% endblock title %}

{% block body %}


<div class="jumbotron">
	<div class="container">
		<h2>Nueva Cancha</h2>
		<form class="form-horizontal" enctype="multipart/form-data" role="form" method="post" id="registerForm">
			{% csrf_token %}
			{% load bootstrap %}
			{{ form|bootstrap_horizontal }}
			<div class="form-group">
				<div class="col-sm-offset-10 col-sm-2">
					<button id="sendB" type="submit" class="btn btn-primary">Crear</button>
				</div>
			</div>
		</form>


	</div>
</div>
{% endblock body %}

website/templates/detalle_complejo.html
{% extends "list.html" %}
{% block search%}
<h1 align="center">Canchas del complejo {{complejo.nombre}}</h1>
{% endblock search%}
{% block buttons_cancha %}
<a class="btn btn-success reservar" href="/cancha/?id={{result.pk}}">Reservar</a>
{% endblock buttons_cancha %}

website/templates/edit_cancha.html
{% extends "base.html" %}
{% block title %}Modificar Cancha{% endblock title %}

{% block body %}


<div class="jumbotron">
	<div class="container">
		<h2>Modificar Cancha</h2>
		<form class="form-horizontal" enctype="multipart/form-data" role="form" method="post" id="registerForm">
			{% csrf_token %}
			{% load bootstrap %}
			{{ form|bootstrap_horizontal }}
			<div class="form-group">
				<div class="col-sm-offset-10 col-sm-2">
					<button id="sendB" type="submit" class="btn btn-primary">Modificar</button>
				</div>
			</div>
		</form>


	</div>
</div>
{% endblock body %}

website/templates/list_canchas_cliente.html
{% extends "list.html" %}
{% block buttons_cancha %}
<a class="btn btn-success reservar" href="/cancha/?id={{result.pk}}">Reservar</a>
{% endblock buttons_cancha %}

website/templates/list_canchas_propietario.html
{% extends "list.html" %}

{% block search %}
<div class="jumbotron center" style="padding-bottom: 0;" >
	

		<a class="btn btn-info col-xs-offset-1" href="/cancha/crearcancha/"><span class="glyphicon glyphicon-plus"></span> Crear Cancha</a>
	
</div>

{% for complejo in complejos %}
	{% for cancha in complejo.cancha_set.all %}
		{{ cancha.precio_por_turno }}
	{% endfor %}
{% endfor %}
{% endblock search %}
{% block buttons_cancha %}
<a class="btn btn-success reservar" href="/cancha/modificar/{{result.pk}}">Modificar</a>
<form id="form_eliminar_{{result.pk}}" role="form" action="/cancha/eliminar/" method="post">
	{% csrf_token %}
	<input name="id_cancha" type="hidden" value="{{result.pk}}">
	<button class="btn btn-danger reservar" style="margin-right: 5px;" type="submit">Eliminar</button>
</form>
{% endblock buttons_cancha %}

{% block empty %}Comenzá a crear tus canchas{% endblock empty %}

website/templates/list_canchas_propietario_1.html
{% extends "base.html" %}

{% block title %}
Reserva la cancha
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/list.css">
{% endblock head%}

{% block body %}

<div class="jumbotron center" style="padding-bottom: 0;" >
	<div class="container">
		<a class="btn btn-info" href="/complejo/crear/"><span class="glyphicon glyphicon-plus"></span> Crear Complejo</a>

		{% if complejos %}
		<a class="btn btn-info" href="/cancha/crear/"><span class="glyphicon glyphicon-plus"></span> Crear Cancha</a>
		{% endif %}
	</div>

</div>

<div class="jumbotron center">
	
	{% if complejos%}
	{% for complejo in complejos %}	
	<div class="container">
	<h2 class="text-center"><strong>Complejo: </strong>{{complejo.nombre}}</h2>
	<h2>Canchas del complejo:</h2>
		<div class="row">
		{% if complejo.cancha_set.all %}

				{% for result in complejo.cancha_set.all %}
					<div class="col-md-6 itemList">
						<div class="col-md-6 element" >
							<img src="{{ result.imagen.url }}">
						</div>
						<div class="col-md-6">
						
							<h4><strong>Deporte: </strong> {{result.deporte.nombre}}</h4>
							<h4><strong>Cancha: </strong> {{result.numero_cancha}}</h4>
							<h4><strong> Precio: </strong>{{result.precio_por_turno}}</h4>

							<a class="btn btn-success reservar" href="/cancha/modificar/{{result.pk}}">Modificar</a>
							<form id="form_eliminar_{{result.pk}}" role="form" action="/cancha/eliminar/" method="post">
								{% csrf_token %}
								<input name="id_cancha" type="hidden" value="{{result.pk}}">
								<button class="btn btn-danger reservar" style="margin-right: 5px;" type="submit">Eliminar</button>
							</form>
						</div>
					</div>

					{% if forloop.counter|divisibleby:2 %}
					</div>
		            <div class="row">
		            {% endif %}
		        {% endfor %}
        			</div>
        	</div>
        {% else %}

        <div class="alert alert-info alert-dismissible" role="alert">
            
            <h3 style="text-align: center;">Este complejo aún no tiene canchas. Puede agregarlas haciendo click en "Crear Cancha"</h3>
     	</div>	
		{% endif %}
        {% endfor %}
		{% else %}
		<div class="container">
		<div class="alert alert-info alert-dismissible" role="alert">
            <h3 style="text-align: center;">¡Aún no tienes complejos! Comienza creando uno.</h3>
     	</div>
     	</div>
		
		{%endif%}
	</div>

</div>
{% endblock body %}

website/templates/recovery.html
{% extends "base.html" %}
{% block title %}Recuperar cuenta{% endblock title %}

{% block body %}


<div class="jumbotron">
	<div class="container">
		{% if messages %}
 
	      {% for message in messages %}
	        <div class="alert alert-info alert-dismissible" role="alert">
	        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	        <strong>{{message}}</strong>
	      </div>
	      {% endfor %}

  		{% endif %}
		<h2>Recuperar cuenta</h2>
		<h5>Ingresa tu nombre de usuario. Enviaremos un correo a la cuenta de email asociada con tu nueva contraseña.</h5>
		<form class="form-horizontal" role="form" method="post" id="recoveryForm">
			{% csrf_token %}
			<div class="container col-sm-offset-3 col-sm-5">
			{% load bootstrap %}
			{{ form|bootstrap_horizontal }}
			</div>
		</form>


	</div>
</div>
{% endblock body %}